# k8s 환경이며 helm이 설치된 경우
# 다음 명령어를 터미널에 입력하면 3306번으로 mysql이 서비스됩니다.

# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# helm install my-mysql -f ./dependencies/helm/mysql.values.yaml bitnami/mysql
# kubectl port-forward service/my-mysql 3306:3306


architecture: standalone
auth:
  # root 사용자 비밀번호
  rootPassword: "root"

  # 생성시 DB를 만들지 여부와 해당 데이터베이스의 이름
  createDatabase: true
  database: "test"

  # 생성할 일반 사용자의 아이디와 비밀번호
  username: "test"
  password: "test"
